"""empty message

Revision ID: ef2824b5bbf0
Revises: 6cd09c5d82a3
Create Date: 2020-02-19 21:45:51.884705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2824b5bbf0'
down_revision = '6cd09c5d82a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friends', 'screenname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friends', sa.Column('screenname', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
